title: The Design Clinic
email: "jacob@thedesignclinic.org"
description: >- # this means to ignore newlines until "baseurl:"
  First Aid for your design needs
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: campjacob
github_username:  campjacob

repository: "campjacob/thedesignclinic.org"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
